title: Colour in p5
hero_image: images/banner.png
description: how to use colour values to draw shapes in p5
version: 4
listed: false
copyedit: false
last_tested: "2021-11-08"
steps:
  - title: Colour in p5
